networks:
  my_net:
volumes:
  my_db:

services:
  api:
    build: .
    container_name: vuttr-api
    ports:
      - "3000:3000"
    networks:
      - my_net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-debian
    container_name: mysql_db
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - my_net
    volumes:
      - "my_db:/var/lib/mysql"
